codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "20...100"
  ignore:
    - "**/*_types.go"
    - "**/*_moq.go"
    - "**/prometheusRules.go"
    - "pkg/config"
    - "pkg/metrics"

  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch: off
    changes: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
