output:
  format: tab
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gosimple:
    checks: ["all", -S1004, -S1008, -S1005, -S1031, -S1011, -S1023, -S1025, -S1034, -S1001]
  staticcheck:
    checks: ["all", -SA4006, -SA9003, -SA5011, -SA4001, -SA4010, SA1019, -SA1030, -SA6000, -SA4009, -SA4022, -SA5001]

presets:
  - bugs
  - error
  - metalinter
  - style
  - unused

run:
  modules-download-mode: vendor
  timeout: 5m