groups:
 - name: rhoam-general.rules
   rules:
    - alert: CriticalMetricsMissing
      annotations:
        message: one or more critical metrics have been missing for 10+ minutes
      expr: absent(rhoam_version) == 1
      for: 10m
      labels:
        severity: critical