# permissions for end users to edit apimanagementtenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimanagementtenant-editor-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - apimanagementtenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - apimanagementtenants/status
  verbs:
  - get
