# permissions for end users to view apimanagementtenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimanagementtenant-viewer-role
rules:
- apiGroups:
  - integreatly.org
  resources:
  - apimanagementtenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - apimanagementtenants/status
  verbs:
  - get
