---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhoam-prometheus-ext
rules:
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - configmaps
      - namespaces
  - verbs:
      - get
    nonResourceURLs:
      - /metrics
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhoam-prometheus-ext
subjects:
  - kind: ServiceAccount
    name: rhoam-prometheus
    namespace: redhat-rhoam-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhoam-prometheus-ext
---
apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: openshift-monitoring-federation
  namespace: redhat-rhoam-operator
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      interval: 120s
      path: /federate
      params:
        'match[]':
          - 'kubelet_volume_stats_used_bytes{endpoint="https-metrics",namespace=~"redhat-rhoam-.*"}'
          - 'kubelet_volume_stats_available_bytes{endpoint="https-metrics",namespace=~"redhat-rhoam-.*"}'
          - 'kubelet_volume_stats_capacity_bytes{endpoint="https-metrics",namespace=~"redhat-rhoam-.*"}'
          - 'haproxy_backend_http_responses_total{route=~"^keycloak.*",exported_namespace=~"redhat-rhoam-.*sso$"}'
          - '{ service="kube-state-metrics", namespace=~".*-rhoam-.*" }'
          - '{ service="node-exporter" }'
          - '{ __name__=~"node_namespace_pod_container:.*" }'
          - '{ __name__=~"node:.*" }'
          - '{ __name__=~"instance:.*" }'
          - '{ __name__=~"container_memory_.*" }'
          - '{ __name__=~":node_memory_.*" }'
          - '{ __name__=~"csv_.*" }'
      relabelings:
        - action: keep
          sourceLabels:
            - __meta_kubernetes_pod_container_port_name
          regex: web
        - action: keep
          regex: prometheus-k8s-0
          sourceLabels:
            - __meta_kubernetes_pod_name
      scheme: https
      scrapeTimeout: 60s
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: openshift-monitoring-federation
  namespaceSelector:
    matchNames:
      - openshift-monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus
---
kind: MonitoringStack
apiVersion: monitoring.rhobs/v1alpha1
metadata:
  name: rhoam
  namespace: redhat-rhoam-operator
spec:
  alertmanagerConfig:
    disabled: false
  namespaceSelector:
    matchExpressions:
      - key: monitoring-key
        operator: In
        values:
          - middleware
  prometheusConfig:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 50Gi
    replicas: 1
  resourceSelector: {}
  resources:
    requests:
      memory: 400Mi
  retention: 45d